change

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -26,6 +26,11 @@ defaults:
 
 jobs:
   build:
+    if: github.repository_owner == 'tardis-sn' &&
+      (github.event_name == 'push' ||
+      github.event_name == 'workflow_dispatch' ||
+      (github.event_name == 'pull_request_target' &&
+      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -51,7 +56,8 @@ jobs:
         if: steps.atom-data-restore.outputs.cache-hit != 'true'
         run: |
           REPO_URL="https://dev.azure.com/tardis-sn/TARDIS/_apis/git/repositories/tardis-refdata"
-          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=main&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
+          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=master&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
+
       - name: Save Atom Data
         uses: actions/cache/save@v4
         if: ${{ steps.atom-data-restore.outputs.cache-hit != 'true'  && always() || false }}
@@ -59,11 +65,12 @@ jobs:
         with:
           path: benchmarks/data/kurucz_cd23_chianti_H_He.h5
           key: atom-data
-      
+
       - name: Copy atom data to refdata
         run: |
           mkdir -p tardis-refdata/atom_data
           cp benchmarks/data/kurucz_cd23_chianti_H_He.h5 tardis-refdata/atom_data/
+
       - name: Setup Mamba
         uses: mamba-org/setup-micromamba@v1
         with:
@@ -74,11 +81,9 @@ jobs:
             python
             asv
             mamba
+
       - name: Install asv
         run: pip install asv
-
-      - run: git remote add upstream https://github.com/AkashKumar7902/tardis.git
-      - run: git fetch upstream master
 
       - name: Accept all asv questions
         run: asv machine --yes
@@ -92,6 +97,7 @@ jobs:
             echo "Some benchmarks have failed!"
             exit 1
           fi
+
       - name: Generate Graphs and HTML
         if: github.event_name != 'pull_request_target'
         run: asv publish
@@ -114,50 +120,53 @@ jobs:
           target-branch: main
           target-directory: .asv
 
-      - run: asv run --config asv.conf.json
-
-      - name: Compare HEAD with main if PR
+      - name: Run benchmarks
         if: github.event_name == 'pull_request_target'
-        continue-on-error: true # TODO: step failed sporadically while testing
-        run: |
-          asv continuous main HEAD | tee asv-cont-output.log  
-          if grep -q failed asv-cont-output.log; then 
-            echo "Some benchmarks have errors!"
-            exit 1
-          fi
-      - name: Compare main and PR head
-        run: asv compare upstream/master HEAD --config asv.conf.json | tee asv-compare-output.log
+        run: asv run --config asv.conf.json
+      
+      - name: Fetch the latest changes
+        if: github.event_name == 'pull_request_target'
+        run: | 
+          git remote add upstream https://github.com/AkashKumar7902/tardis.git
+          git fetch upstream master
 
-      - name: Compare main and PR head but only show changed results
-        run: asv compare upstream/master HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
+      - name: Compare Master and PR head
+        run: asv compare ${{ github.event_name.pull_request.base.sha }} ${{ github.event_name.pull_request.head.sha }} --config asv.conf.json | tee asv-compare-output.log
+
+      - name: Compare Master and PR head but only show changed results
+        run: asv compare ${{ github.event_name.pull_request.base.sha }} ${{ github.event_name.pull_request.head.sha }} --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
-        id: asv_pr_vs_main
+        id: asv_pr_vs_master
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-output.log
 
       - name: Benchmarks compare only changed output
-        id: asv_pr_vs_main_changed
+        id: asv_pr_vs_master_changed
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
 
+      - name: Remove .asv
+        run: rm -rf .asv
+
       - name: Run benchmarks for base to head commits of PR
         if: github.event_name == 'pull_request_target'
         run: |
-          asv run ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tee asv-output-PR.log  
-          if grep -q failed asv-output-PR.log; then 
-            echo "Some benchmarks have failed!"
-            exit 1
-          fi
+          asv run master..${{ github.ref_name }} | tee asv-output-PR.log  
+            if grep -q failed asv-output-PR.log; then 
+              echo "Some benchmarks have failed!"
+              exit 1
+            fi
           mkdir -p PR-${{ github.event.number }}
-          cd PR-${{ github.event.number }}
-          
+          cp -r .asv PR-${{ github.event.number }}
+      
       - name: Generate Graphs and HTML of PR
         if: github.event_name == 'pull_request_target'
-        working-directory: PR-${{ github.event.number }}
-        run: asv publish
+        run: |
+          cd PR-${{ github.event.number }}
+          asv publish
 
       - name: Delete env files of PR
         if: github.event_name == 'pull_request_target'
@@ -176,6 +185,7 @@ jobs:
           user-email: tardis.sn.bot@gmail.com
           target-branch: main
           target-directory: PR
+
       
       - name: Find Comment
         if: always() && github.event_name == 'pull_request_target'
@@ -196,24 +206,32 @@ jobs:
           body: |
             *\*beep\* \*bop\**
             Hi human, 
-            I ran benchmarks as you asked comparing main (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
+            I ran benchmarks as you asked comparing master (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
             Here are the logs produced by ASV.
             Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
+
             Significantly changed benchmarks:
             <details>
+
               ```diff
-              ${{ steps.asv_pr_vs_main_changed.outputs.content }}
+              ${{ steps.asv_pr_vs_master_changed.outputs.content }}
               ```
+
             </details>
+
             All benchmarks:
             <details>
+
               ```diff
-              ${{ steps.asv_pr_vs_main.outputs.content }}
+              ${{ steps.asv_pr_vs_master.outputs.content }}
               ```
               
             </details>
+
+            If you want to see the graph of the results, you can check it [**here**](${{ env.URL_PAGES }})
         env:
           URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
+          URL_PAGES: https://tardis-sn.github.io/tardis-benchmarks/PR-${{ github.event.number }}
 
       - name: Save results artifact
         uses: actions/upload-artifact@v4
@@ -222,6 +240,5 @@ jobs:
           name: asv-benchmark-results-${{ runner.os }}
           path: |
             .asv/results
-            asv-cont-output.log  
             asv-compare-output.log
             asv-compare-changed-output.log
