github actions benchmark refactor
Signed-off-by: Akash Kumar <meakash7902@gmail.com>

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -3,11 +3,11 @@ name: benchmarks
 on:
   push:
     branches:
-      - master
+      - main
 
   pull_request_target:
     branches:
-      - master
+      - main
 
     types:
       - opened
@@ -26,11 +26,6 @@ defaults:
 
 jobs:
   build:
-    if: github.repository_owner == 'tardis-sn' &&
-      (github.event_name == 'push' ||
-      github.event_name == 'workflow_dispatch' ||
-      (github.event_name == 'pull_request_target' &&
-      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -56,7 +51,7 @@ jobs:
         if: steps.atom-data-restore.outputs.cache-hit != 'true'
         run: |
           REPO_URL="https://dev.azure.com/tardis-sn/TARDIS/_apis/git/repositories/tardis-refdata"
-          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=master&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
+          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=main&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
 
       - name: Save Atom Data
         uses: actions/cache/save@v4
@@ -115,34 +110,68 @@ jobs:
           target-branch: main
           target-directory: .asv
 
-      - name: Compare HEAD with master if PR
+      - name: Compare HEAD with main if PR
         if: github.event_name == 'pull_request_target'
         continue-on-error: true # TODO: step failed sporadically while testing
         run: |
-          asv continuous ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-cont-output.log  
+          asv continuous main HEAD | tee asv-cont-output.log  
           if grep -q failed asv-cont-output.log; then 
             echo "Some benchmarks have errors!"
             exit 1
           fi
 
-      - name: Compare Master and PR head
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-compare-output.log
+      - name: Compare main and PR head
+        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --config asv.conf.json | tee asv-compare-output.log
 
-      - name: Compare Master and PR head but only show changed results
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed | tee asv-compare-changed-output.log
+      - name: Compare main and PR head but only show changed results
+        run: asv compare main HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
-        id: asv_pr_vs_master
+        id: asv_pr_vs_main
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-output.log
 
       - name: Benchmarks compare only changed output
-        id: asv_pr_vs_master_changed
+        id: asv_pr_vs_main_changed
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
 
+      - name: Run benchmarks for base to head commits of PR
+        if: github.event_name == 'pull_request_target'
+        run: |
+          mkdir -p PR-${{ github.event.number }}
+          cd PR-${{ github.event.number }}
+          asv run ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tee asv-output-PR.log  
+          if grep -q failed asv-output-PR.log; then 
+            echo "Some benchmarks have failed!"
+            exit 1
+          fi
+
+      - name: Generate Graphs and HTML of PR
+        if: github.event_name == 'pull_request_target'
+        working-directory: PR-${{ github.event.number }}
+        run: asv publish
+
+      - name: Delete env files of PR
+        if: github.event_name == 'pull_request_target'
+        run: rm -r PR-${{ github.event.number }}/.asv/env
+
+      - name: Push results of PR to results repository
+        if: github.event_name == 'pull_request_target'
+        continue-on-error: true
+        uses: cpina/github-action-push-to-another-repository@main 
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN }}
+        with:
+          source-directory: PR-${{ github.event.number }}
+          destination-github-username: tardis-sn
+          destination-repository-name: tardis-benchmarks
+          user-email: tardis.sn.bot@gmail.com
+          target-branch: main
+          target-directory: PR
+      
       - name: Find Comment
         if: always() && github.event_name == 'pull_request_target'
         uses: peter-evans/find-comment@v1
@@ -162,14 +191,15 @@ jobs:
           body: |
             *\*beep\* \*bop\**
             Hi human, 
-            I ran benchmarks as you asked comparing master (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
+            I ran benchmarks as you asked comparing main (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
             Here are the logs produced by ASV.
             Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
+
             Significantly changed benchmarks:
             <details>
 
               ```diff
-              ${{ steps.asv_pr_vs_master_changed.outputs.content }}
+              ${{ steps.asv_pr_vs_main_changed.outputs.content }}
               ```
 
             </details>
@@ -178,7 +208,7 @@ jobs:
             <details>
 
               ```diff
-              ${{ steps.asv_pr_vs_master.outputs.content }}
+              ${{ steps.asv_pr_vs_main.outputs.content }}
               ```
               
             </details>
