change

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -1,23 +1,29 @@
 name: benchmarks
+
 on:
   push:
     branches:
       - master
+
   pull_request_target:
     branches:
       - master
+
     types:
       - opened
       - reopened
       - synchronize
       - labeled # benchmarks label required
   workflow_dispatch:
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
   cancel-in-progress: true
+
 defaults:
   run:
     shell: bash -l {0}
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -26,23 +32,26 @@ jobs:
         if: github.event_name != 'pull_request_target'
         with:
           fetch-depth: 0
+
       - name: Checkout pull/${{ github.event.number }}
         uses: actions/checkout@v4
         with:
           ref: ${{ github.sha }}
           fetch-depth: 0
         if: github.event_name == 'pull_request_target'
+
       - name: Restore Atom Data
         uses: actions/cache/restore@v4
         id: atom-data-restore
         with:
           path: benchmarks/data/kurucz_cd23_chianti_H_He.h5
           key: atom-data
+
       - name: Download Atom Data
         if: steps.atom-data-restore.outputs.cache-hit != 'true'
         run: |
           REPO_URL="https://dev.azure.com/tardis-sn/TARDIS/_apis/git/repositories/tardis-refdata"
-          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=master&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
+          wget -q "$REPO_URL/items?path=atom_data/kurucz_cd23_chianti_H_He.h5&versionType=branch&version=main&resolveLfs=true" -O benchmarks/data/kurucz_cd23_chianti_H_He.h5
       - name: Save Atom Data
         uses: actions/cache/save@v4
         if: ${{ steps.atom-data-restore.outputs.cache-hit != 'true'  && always() || false }}
@@ -50,6 +59,7 @@ jobs:
         with:
           path: benchmarks/data/kurucz_cd23_chianti_H_He.h5
           key: atom-data
+      
       - name: Copy atom data to refdata
         run: |
           mkdir -p tardis-refdata/atom_data
@@ -66,23 +76,30 @@ jobs:
             mamba
       - name: Install asv
         run: pip install asv
+
+      - run: git remote add upstream https://github.com/AkashKumar7902/tardis.git
+      - run: git fetch upstream master
+
       - name: Accept all asv questions
         run: asv machine --yes
+
       - name: Run benchmarks for last 5 commits if not PR
         if: github.event_name != 'pull_request_target'
         run: |
           git log -n 5  --pretty=format:"%H" >> tag_commits.txt
-          asv run HASHFILE:tag_commits.txt | tee asv-output.log
-          if grep -q failed asv-output.log; then
+          asv run HASHFILE:tag_commits.txt | tee asv-output.log  
+          if grep -q failed asv-output.log; then 
             echo "Some benchmarks have failed!"
             exit 1
           fi
       - name: Generate Graphs and HTML
         if: github.event_name != 'pull_request_target'
         run: asv publish
+
       - name: Delete env files
         if: github.event_name != 'pull_request_target'
         run: rm -r .asv/env
+
       - name: Push results to results repository
         if: github.event_name != 'pull_request_target'
         continue-on-error: true
@@ -95,50 +112,60 @@ jobs:
           destination-repository-name: tardis-benchmarks
           user-email: tardis.sn.bot@gmail.com
           target-branch: main
-          target-directory: .asv      
+          target-directory: .asv
 
-      - name: Run benchmarks
+      - run: asv run --config asv.conf.json
+
+      - name: Compare HEAD with main if PR
         if: github.event_name == 'pull_request_target'
-        run: asv run
-      - run: git remote add upstream https://github.com/AkashKumar7902/tardis.git
-      - run: git fetch upstream master
-      - name: Compare Master and PR head
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-compare-output.log
-      - name: Compare Master and PR head but only show changed results
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed | tee asv-compare-changed-output.log
+        continue-on-error: true # TODO: step failed sporadically while testing
+        run: |
+          asv continuous main HEAD | tee asv-cont-output.log  
+          if grep -q failed asv-cont-output.log; then 
+            echo "Some benchmarks have errors!"
+            exit 1
+          fi
+      - name: Compare main and PR head
+        run: asv compare upstream/master HEAD --config asv.conf.json | tee asv-compare-output.log
+
+      - name: Compare main and PR head but only show changed results
+        run: asv compare upstream/master HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
+
       - name: Benchmarks compare output
-        id: asv_pr_vs_master
+        id: asv_pr_vs_main
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-output.log
+
       - name: Benchmarks compare only changed output
-        id: asv_pr_vs_master_changed
+        id: asv_pr_vs_main_changed
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
+
       - name: Run benchmarks for base to head commits of PR
         if: github.event_name == 'pull_request_target'
         run: |
-          asv run ${{ github.ref_name }} | tee asv-output-PR.log
-          if grep -q failed asv-output-PR.log; then
+          mkdir -p PR-${{ github.event.number }}
+          cd PR-${{ github.event.number }}
+          asv run ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tee asv-output-PR.log  
+          if grep -q failed asv-output-PR.log; then 
             echo "Some benchmarks have failed!"
             exit 1
           fi
-          mkdir -p PR-${{ github.event.number }}
-          cp -r .asv PR-${{ github.event.number }}
-          
       - name: Generate Graphs and HTML of PR
         if: github.event_name == 'pull_request_target'
-        run: |
-          cd PR-${{ github.event.number }}
-          asv publish
+        working-directory: PR-${{ github.event.number }}
+        run: asv publish
+
       - name: Delete env files of PR
         if: github.event_name == 'pull_request_target'
         run: rm -r PR-${{ github.event.number }}/.asv/env
+
       - name: Push results of PR to results repository
         if: github.event_name == 'pull_request_target'
         continue-on-error: true
-        uses: cpina/github-action-push-to-another-repository@main
+        uses: cpina/github-action-push-to-another-repository@main 
         env:
           API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN }}
         with:
@@ -148,6 +175,7 @@ jobs:
           user-email: tardis.sn.bot@gmail.com
           target-branch: main
           target-directory: PR
+      
       - name: Find Comment
         if: always() && github.event_name == 'pull_request_target'
         uses: peter-evans/find-comment@v1
@@ -155,6 +183,7 @@ jobs:
         with:
           issue-number: ${{ github.event.number }}
           body-includes: I ran benchmarks as you asked
+
       - name: Post comment
         if: github.event_name == 'pull_request_target'
         uses: peter-evans/create-or-update-comment@v2
@@ -165,24 +194,26 @@ jobs:
           edit-mode: replace
           body: |
             *\*beep\* \*bop\**
-            Hi human,
-            I ran benchmarks as you asked comparing master (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}).
+            Hi human, 
+            I ran benchmarks as you asked comparing main (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
             Here are the logs produced by ASV.
-            Results can also be downloaded as artifacts [**here**](${{ env.URL }}).
+            Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
             Significantly changed benchmarks:
             <details>
               ```diff
-              ${{ steps.asv_pr_vs_master_changed.outputs.content }}
+              ${{ steps.asv_pr_vs_main_changed.outputs.content }}
               ```
             </details>
             All benchmarks:
             <details>
               ```diff
-              ${{ steps.asv_pr_vs_master.outputs.content }}
+              ${{ steps.asv_pr_vs_main.outputs.content }}
               ```
+              
             </details>
         env:
           URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
+
       - name: Save results artifact
         uses: actions/upload-artifact@v4
         if: always()
@@ -190,5 +221,6 @@ jobs:
           name: asv-benchmark-results-${{ runner.os }}
           path: |
             .asv/results
+            asv-cont-output.log  
             asv-compare-output.log
             asv-compare-changed-output.log
